-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 12:05:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema klimachallengeFS22
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `klimachallengeFS22` ;

-- -----------------------------------------------------
-- Schema klimachallengeFS22
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `klimachallengeFS22` DEFAULT CHARACTER SET utf8 ;
USE `klimachallengeFS22` ;

-- -----------------------------------------------------
-- Table `klimachallengeFS22`.`Grids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klimachallengeFS22`.`Grids` (
  `id_Grid` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Altitude` INT NOT NULL,
  `Longitude` DECIMAL(5,2) NOT NULL,
  `Latitude` DECIMAL(5,2) NOT NULL,
   PRIMARY KEY (`id_Grid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `klimachallengeFS22`.`Historical Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klimachallengeFS22`.`Temperature` (
  `id_Temperature` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Temperature_Max` DECIMAL(10,2) NOT NULL,
  `Grids_id_Grid` INT NOT NULL,
  PRIMARY KEY (`id_Temperature`),
  INDEX `fk_Temperature_Grids_idx` (`Grids_id_Grid` ASC) VISIBLE,
  CONSTRAINT `fk_Temperature_Grids`
    FOREIGN KEY (`Grids_id_Grid`)
    REFERENCES `klimachallengeFS22`.`Grids` (`id_Grid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `klimachallengeFS22`.`Threshold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klimachallengeFS22`.`Threshold` (
  `id_Threshold` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Threshold_Temperature` DECIMAL(10,6) NOT NULL,
  `Grids_id_Grid` INT NOT NULL,
  PRIMARY KEY (`id_Threshold`),
  INDEX `fk_Threshold_Grids_idx` (`Grids_id_Grid` ASC) VISIBLE,
  CONSTRAINT `fk_Threshold_Grids`
    FOREIGN KEY (`Grids_id_Grid`)
    REFERENCES `klimachallengeFS22`.`Grids` (`id_Grid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `klimachallengeFS22`.`Magnitude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klimachallengeFS22`.`Magnitude` (
  `id_Magnitude` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Magnitude` DECIMAL(10,6) NOT NULL,
  `Grids_id_Grid` INT NOT NULL,
  PRIMARY KEY (`id_Magnitude`),
  INDEX `fk_Magnitude_Grids_idx` (`Grids_id_Grid` ASC) VISIBLE,
  CONSTRAINT `fk_Magnitude_Grids`
    FOREIGN KEY (`Grids_id_Grid`)
    REFERENCES `klimachallengeFS22`.`Grids` (`id_Grid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
